version: "2.1"

volumes:
  state: {}

services:
  tailscale:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - state:/var/lib/tailscale
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    labels:
      - io.balena.features.kernel-modules=1
    cap_add:
      - net_admin
      - net_raw
      - sys_module
    tmpfs:
      - /tmp
      - /var/run/
