version: "2.1"

volumes:
  ts-state: {}

services:
  tailscale:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    restart: on-failure
    volumes:
      - ts-state:/var/lib/tailscale
    labels:
      - io.balena.features.kernel-modules=1
    cap_add:
      - net_admin
      - sys_module
    tmpfs:
      - /tmp
      - /var/run/
