version: "2.1"

volumes:
  state: {}

services:
  tailscale:
    build:
      context: .
      dockerfile: Dockerfile.template
    network_mode: host
    volumes:
      - state:/tailscale
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    labels:
      - io.balena.features.kernel-modules=1
    cap_add:
      - net_admin
      - sys_module

  hostname:
    build:
      context: hostname
      dockerfile: Dockerfile.template
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: tailscale
