name: balena

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        fleet:
          [
            gh_klutchell/tailscale-aarch64,
            gh_klutchell/tailscale-amd64,
            gh_klutchell/tailscale-armv7hf,
          ]

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
          fetch-depth: 1
      # https://github.com/balena-io/deploy-to-balena-action
      - uses: balena-io/deploy-to-balena-action@f7d434197ec7d57218da93bf9c720e4c14c6b197 # v2.0.131
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          fleet: ${{ matrix.fleet }}
