name: balena

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        fleet:
          [
            gh_klutchell/tailscale-aarch64,
            gh_klutchell/tailscale-amd64,
            gh_klutchell/tailscale-armv7hf,
          ]

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 1
      # https://github.com/balena-io/deploy-to-balena-action
      - uses: balena-io/deploy-to-balena-action@5328e4539efc9dc95a0471c8fcf4bd16fc75e70d # v2.0.120
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          fleet: ${{ matrix.fleet }}
