name: balena

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        fleet:
          [
            klutchell_blocks/tailscale-aarch64,
            klutchell_blocks/tailscale-amd64,
            klutchell_blocks/tailscale-armv7hf,
          ]

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: balena-io/deploy-to-balena-action@9d553d05baab3a9398cc0469587cbc2c39f075d3 # v2.0.29
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          fleet: ${{ matrix.fleet }}
          create_tag: true
